DEFAULT_SETTINGS = {
    "database": {
        "engine": "sqlite",
        "sqlite_path": "data/paper2data.db",
        "host": "localhost",
        "port": 3306,
        "user": "root",
        "password": "",
        "database": "paper2data",
        "charset": "utf8mb4",
        "table_raw": "papers_raw",
        "table_relevant": "papers_relevant",
        "table_queue": "paper_queue",
        "table_config": "system_config",
    },
    "research_description": "请在这里填写你的研究方向描述",
    "arxiv": {
        "keywords": ["cs.CL", "cs.CV", "cs.LG"],
        "max_results_per_keyword": None,
        "batch_size": 50,
        "request_delay": 30,
        "consecutive_duplicate_threshold": 10,
        "recent_days": 3,
        "api_url": "http://export.arxiv.org/api/query",
    },
    "llm_filter": {
        "enable": True,
        "backend": "openclaw",
        "api_key": "",
        "base_url": "https://openrouter.ai/api/v1",
        "model": "google/gemini-3.1-flash-lite-preview",
        "temperature": 0.5,
        "max_tokens": 4096,
        "min_score": 60,
        "min_stars": 60,
        "save_all_papers": True,
        "max_workers": 4,
        "scoring_anchors": "",
        "openclaw": {
            "binary_path": "openclaw",
            "translation_agent_id": "daliy_paper-translation",
            "filter_agent_id": "daliy_paper-filter",
            "review_agent_id": "daliy_paper-graduate-student",
            "translation_model": "",
            "filter_model": "",
            "review_model": "",
            "timeout_seconds": 300,
            "use_local": False,
        },
    },
    "openclaw": {
        "enabled": True,
        "delivery_mode": "cli-session",
        "delivery_channel": "",
        "delivery_target": "",
        "delivery_account_id": "",
        "binary_path": "openclaw",
        "session_key": "main",
        "timeout_seconds": 300,
        "max_papers_per_message": 5,
        "include_full_abstract": False,
        "enable_graduate_student_briefing": False,
    },
    "schedule": {
        "enable_schedule": True,
        "timezone": "Asia/Shanghai",
        "fetch_papers": {
            "enable": True,
            "time": "02:00",
            "backlog_limit": 50,
        },
        "process_papers": {
            "batch_size": 100,
        },
        "push_papers": {
            "enable": True,
            "times": ["09:00"],
            "max_papers_per_push": 5,
            "min_interval_minutes": 60,
        },
    },
    "logging": {
        "level": "INFO",
        "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        "log_file": "logs/daily_paper.log",
    },
    "output": {
        "save_to_file": True,
        "output_dir": "output",
        "filename_format": "arxiv_papers_{date}.csv",
    },
}
